### ISSUE TITLE
TypeError: filter() missing 1 required positional argument: 'record' caused by socket timeout

### ISSUE THREAD

**Issue by josteinaj** [airbrake/pybrake#167]
This might be a similar issue as #130, I'm not sure.

I keep getting this error in the logs:

```
2021-12-07 20:32:55,840 routes.py:113 pybrake ERROR - The read operation timed out
2021-12-07 20:32:55,840 ERROR    The read operation timed out
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pybrake/routes.py", line 109, in _flush
    resp = urllib.request.urlopen(req, timeout=5)
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 1299, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pybrake/routes.py", line 113, in _flush
    logger.error(err)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 948, in handle
    rv = self.filter(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
TypeError: filter() missing 1 required positional argument: 'record'
```

They're mostly just annoying, I don't think they cause any problems in our applications.

**Comment by scottsbaldwin** [comment]
Thanks @josteinaj for reporting this. You're right, these exceptions should not be impacting your application. They indicate there was a problem asynchronously reporting error information to the Airbrake service.

Can you confirm which version of pybrake you are using?

**Comment by josteinaj** [comment]
Oh, sorry, forgot about the version.

I realize it's an old version at this point:
pybrake==0.4.2

I will upgrade and see if the exception is still there.

**Comment by josteinaj** [comment]
Same error with pybrake==1.0.4.

```
127.0.0.1 - - [09/Dec/2021:20:51:52 +0000] "GET /datawarehouse/v1/health/ HTTP/1.1" 200 85 "-" "curl/7.74.0"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pybrake/routes.py", line 109, in _flush
    resp = urllib.request.urlopen(req, timeout=5)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 1177, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pybrake/routes.py", line 113, in _flush
    logger.error(err)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 890, in handle
    rv = self.filter(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
TypeError: filter() missing 1 required positional argument: 'record'

2021-12-09 20:51:53,957 routes.py:113 pybrake ERROR - The read operation timed out
```

**Comment by scottsbaldwin** [comment]
@josteinaj are you still experiencing this issue? If so, are you able to reproduce this in a non-production environment? I'm wondering what the URL (from `self._ab_url()`)  is at runtime for you in https://github.com/airbrake/pybrake/blob/master/pybrake/routes.py#L105:

```
        req = urllib.request.Request(
            self._ab_url(), data=out, headers=self._ab_headers, method="POST"
        )
```

**Comment by smurf-U** [comment]
@josteinaj I attempted to reproduce the problem in several ways but was unable to do so. It appears to me that there is a problem with the logging package in your environment.

I'm curious as to why the [URL](https://github.com/airbrake/pybrake/blob/af9081b1fc4432dda1fdd414ab76242d8f309051/pybrake/routes.py#L156) gives timeouts in your environment. If you're still having problems with the surroundings, Please try once using the examples included in the package.

**Comment by josteinaj** [comment]
Thanks.

I'm sorry I haven't gotten around to looking more into this.

Here's the dependencies used in the environment where I see this error, in case it's relevant:

```
#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile requirements.txt
#
accumulation-tree==0.6.2
    # via tdigest
authlib==0.15.5
    # via -r requirements.txt
banal==1.0.6
    # via
    #   -r requirements.txt
    #   languagecodes
blinker==1.4
    # via -r requirements.txt
certifi==2021.10.8
    # via requests
cffi==1.15.0
    # via cryptography
charset-normalizer==2.0.8
    # via requests
click==8.0.3
    # via flask
cryptography==36.0.0
    # via authlib
flask==2.0.2
    # via -r requirements.txt
idna==3.3
    # via requests
itsdangerous==2.0.1
    # via flask
jinja2==3.0.3
    # via flask
languagecodes==1.1.1
    # via -r requirements.txt
markupsafe==2.0.1
    # via jinja2
mysql-connector==2.2.9
    # via -r requirements.txt
psutil==5.8.0
    # via -r requirements.txt
pybrake==1.0.4
    # via -r requirements.txt
pycparser==2.21
    # via cffi
python-dateutil==2.8.2
    # via -r requirements.txt
pyudorandom==1.0.0
    # via tdigest
pyyaml==6.0
    # via -r requirements.txt
requests==2.26.0
    # via -r requirements.txt
six==1.16.0
    # via python-dateutil
tdigest==0.5.2.2
    # via pybrake
urllib3==1.26.7
    # via requests
werkzeug==2.0.2
    # via flask
```

**Comment by smurf-U** [comment]
@josteinaj I tried with the same environment, but no exceptions were thrown. As a result, I'm closing this issue for now. As mention please try to with sample [example](https://github.com/airbrake/pybrake/tree/master/examples) given in package.

**Comment by josteinaj** [comment]
Ok, thanks for trying! I will reopen if I can reproduce it or know more.

**Comment by josteinaj** [comment]
The URL in https://github.com/airbrake/pybrake/blob/9829a711b8a2b442a60291abe4b2970ede5cdd9b/pybrake/routes.py#L105 is  `https://api.airbrake.io/api/v5/projects/PROJECTID/routes-stats` (where I've replaced my project ID with PROJECTID). So it seems correct.

(Just adding this as a note here for the record. I won't have time to debug more for now anyway.)
